### ISSUE TITLE
Web page opens print dialog on iOS

### ISSUE THREAD

**Issue by MarcusE1W** [clojerl/try_clojerl#58] opened 2018-07-29 13:45 UTC
Hi.
A very interesting project.

When I open the http://try.clojerl.online/ web page it immediately opens the print dialog (as in print to paper) of iOS. the preview screen shows just the full web page.
I can click that away but I am not sure if that’s intended.

**Comment by jfacorro** [comment] 2020-07-24 20:27
@MarcusE1W I missed this issue, sorry for that. That behaviour is not expected, I will look into it.

**Comment by jfacorro** [comment] 2020-07-27 12:12
Sadly I couldn't reproduce this behaviour on an iOS device. I will close the issue. Please re-open if you still see this happening.

**Closed by jfacorro** 2020-07-27 12:12 UTC
